#!/bin/sh

echo 'Ensure resources..'

docker compose -f ./local/compose.yml exec -u "$(id -u):$(id -g)" auth python manage.py makemessages -l en -e py
docker compose -f ./local/compose.yml exec -u "$(id -u):$(id -g)" auth python manage.py compilemessages
docker compose -f ./local/compose.yml exec -u "$(id -u):$(id -g)" auth python manage.py collectstatic --no-input

echo 'Building images..'

docker build \
  --build-arg WWWUSER="$(id -u)" \
  --build-arg WWWGROUP="$(id -g)" \
  --target local-portable \
  --tag auth-server:local-portable \
  --rm \
  .
