#!/bin/sh

display_separator() {
    printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
}

display_separator
echo 'Restarting docker service..'
docker compose -f ./local/compose.yml up -d --force-recreate auth
